name: 毎日天気を通知する

on:
  schedule:
    # 毎日日本時間の朝6時（世界標準時の前日21時）に自動実行する設定
    - cron: '0 21 * * *'
  # GitHubの画面から手動で「今すぐ動かす」ボタンを押せるようにする設定（テスト用）
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト（取得）
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Pythonのセットアップ
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: '3.11'

      - name: 必要なライブラリのインストール
        run: |
          pip install line-bot-sdk requests

      - name: Pythonプログラムを実行
        env:
          LINE_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER: ${{ secrets.USER_ID }}
        run: python weather_line.py
